# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3cf496b98130bd0f60946406611da03f3b06d8070591e0105369eabebd0244a35fa72b4e3e4d4f7c6e6820238e8c51480d287bf17169fea4d382d48dcb893653

test:
  secret_key_base: e762c710dc4729822ed481280f99cd6a0724d600b7beb9b3fe44eacd70289dd94c2210a7dd9d5cddef0dbb51beff821d0e0452ce4cb0784909969adad6d792d7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
